### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tomasonjo** [SapienzaNLP/relik#8] opened 2024-08-08 11:53 UTC
Luckily, quite deterministic. To reproduce:

```
from relik import Relik
from relik.inference.data.objects import RelikOutput

text = """GOOGL - 3 Revolutionary Stocks I'd Buy Right Now Without Hesitation:  2023 - 06 - 15 05:54:00 ET 
 The Beatles memorialized the line , " You say you want a revolution . " Investors might not realize ET , but Investors 've experienced several revolutions in recent years with more to come . 
 Technological advances are changing life as we know life . And some companies are both profiting from those advances and giving investors an opportunity to profit . Here are three revolutionary stocks I 'd buy right now . 
 The world is different now than world was 20 years ago in multiple ways thanks to Alphabet ( NASDAQ : GOOG ) ( NASDAQ : GOOGL ) . Google has become a verb . YouTube regularly attracts more viewers than TV networks do . 
 Continue reading 
 For further details see : 
 3 Revolutionary Stocks I 'd Buy Right Now Without Hesitation 
 Market Wire News is a media platform , the information on this page was provided by Motley Fool via Quote Media . Read our full disclaimer ."""

relik = Relik.from_pretrained("relik-ie/relik-cie-small")
relik(text)
```

Full trace:

> IndexError                                Traceback (most recent call last)
> [<ipython-input-17-0dc86c166fd7>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 relik(document.text)
> 
> [/usr/local/lib/python3.10/dist-packages/relik/inference/annotator.py](https://localhost:8080/#) in __call__(self, text, windows, candidates, mentions, top_k, window_size, window_stride, is_split_into_words, retriever_batch_size, reader_batch_size, return_windows, use_doc_topic, annotation_type, progress_bar, **kwargs)
>     549         for task_type, task_candidates in windows_candidates.items():
>     550             for i, task_candidate in enumerate(task_candidates):
> --> 551                 windows[i]._d[f"{task_type.value}_candidates"] = task_candidate
>     552 
>     553         windows = windows + blank_windows
> 
> IndexError: list index out of range

**Comment by LittlePea13** [comment] 2024-08-08 12:21
I am looking at this at the moment, it is due to some windows with empty predictions. Will be fixed shortly.

**Closed** 2024-08-08 12:43 UTC

**Comment by narayanacharya6** [comment] 2024-08-20 16:10
Can a version with this fix be released on pypi. I don't see the fix available in v1.0.5.

**Comment by LittlePea13** [comment] 2024-08-21 01:01
It should be already in v1.0.5, did you get this same error with that version? Was it with this example or can you provide a way to reproduce it?

**Comment by narayanacharya6** [comment] 2024-08-26 11:42
Yes, I get the same error with v1.0.5 for the same example as mentioned above.

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/02748ae9-2988-4f1d-a9f0-cdae3b76ee84">

**Comment by narayanacharya6** [comment] 2024-08-28 08:26
I might be wrong but I don't think it the model files or them being cached. If you look at the change log of the v1.0.5 release [here](https://github.com/SapienzaNLP/relik/compare/1.0.4...1.0.5) it does not include the commit with `515ac1a` which has the fix for this issue.

I have the latest version installed:
```
$ pip list | grep relik
relik                    1.0.5
```

And I also checked one of the files in the package and if the changes from commit `515ac1a` are visible but I don't see it:
```$ sed -n 835,845p /opt/conda/envs/narayan-relik-cpu/lib/python3.10/site-packages/relik/reader/pytorch_modules/hf/modeli
ng_relik.py
            if (not is_prediction and not is_validation)
            else (ned_start_predictions, ned_end_predictions)
        )

        start_counts = (start_position > 0).sum(1)
        if (start_counts > 0).any():
            ned_end_predictions = ned_end_predictions.split(start_counts.tolist())
        # limit to 30 predictions per document using start_counts, by setting all po after sum is 30 to 0
        # if is_validation or is_prediction:
        #     ned_start_predictions[ned_start_predictions == 1] = start_counts
        # We can only predict relations if we have start and end predictions
```

Notice that else condition for `if (start_counts > 0).any():` which was introduced in the fix is not available.

**Comment by LittlePea13** [comment] 2024-08-28 10:07
Oh that's embarrassing, sorry about that and making you lose time. You are absolutely right, in fact I pushed that fix after 1.0.5 was already up 😅. We will remedy it in the next update in pypi. Thanks for bringing it up.

**Comment by narayanacharya6** [comment] 2024-08-28 10:23
No problem. Thank you! :)

**Comment by LittlePea13** [comment] 2024-09-05 13:32
@narayanacharya6 It was pushed yesterday, version 1.0.6
